#!/bin/bash -e

# https://www.gnu.org/software/coreutils/coreutils.html
coreutils () {
    COMMAND=$1
    shift

    # OS X coreutils commands are prefixed with g
    if [ ! -z "$(which g$COMMAND)" ]; then
        COMMAND=g$COMMAND
    fi

    $COMMAND $@
}

coreutils timeout $@
